CREATE DATABASE IF NOT EXISTS zoo;
USE zoo;
CREATE TABLE IF NOT EXISTS admins (
	Admin_ID INT NOT NULL AUTO_INCREMENT,
    User_Name VARCHAR(255) NOT NULL UNIQUE,
    Tc_No VARCHAR(11) NOT NULL UNIQUE,
    E_Mail VARCHAR(255) NOT NULL UNIQUE,
    First_Name VARCHAR(255) NOT NULL,
    Last_Name VARCHAR(255) NOT NULL,
    GSM_No VARCHAR(10) NOT NULL UNIQUE,
    Birth_Date DATE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (`Admin_ID`)
);
CREATE TABLE IF NOT EXISTS users (
	User_ID INT NOT NULL AUTO_INCREMENT,
    User_Name VARCHAR(255) NOT NULL UNIQUE,
    Tc_No VARCHAR(11) NOT NULL UNIQUE,
    E_Mail VARCHAR(255) NOT NULL UNIQUE,
    First_Name VARCHAR(255) NOT NULL,
    Last_Name VARCHAR(255) NOT NULL,
    GSM_No VARCHAR(10) NOT NULL UNIQUE,
    Birth_Date DATE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (`User_ID`)
);
CREATE TABLE IF NOT EXISTS animals (
	Animal_ID INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Species VARCHAR(255) NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    Birth_Date DATE NOT NULL,
    Habitat VARCHAR(255) NOT NULL,
    Health_Status VARCHAR(255) NOT NULL,
    Nutrition_Type VARCHAR(255) NOT NULL,
    Nutrition_Quantity VARCHAR(255) NOT NULL,
    Nutrition_Times VARCHAR(255) NOT NULL,
    PRIMARY KEY (`Animal_ID`)
);
